Add dockerfile profile to java launch.config files to fix k8s deployments
GoogleCloudPlatform/cloud-code-samples pull request #1224
Opened 2023-03-16 21:26 UTC by SKrupa

Currently, Cloud Code defaults to using cloudbuild if a user opens samples.workspace and tries to deploy the java samples to k8s due to maven changes (see: https://github.com/GoogleCloudPlatform/cloud-code-samples/pull/1207)

2023-03-16 21:30 UTC, davidponder approved these changes

2023-03-16 21:32 UTC, davidponder requested changes

2023-03-16 21:32 UTC, davidponder commented on java/java-hello-world/.vscode/launch.json
> +        "imageRegistry": "gcr.io/cloud-code-vs-code"
I don't think this should be filled in (users can specify their own imageRegistry i think)

2023-03-17 19:59 UTC, davidponder approved these changes

2023-03-20 23:29 UTC, averikitsch approved these changes
Ultimately, I would like to use the cloudbuild profile, because Jib is a better containerization method than a Dockerfile. However, that is dependent on a maintained Cloud Builders with both Skaffold and Maven installed.

2023-03-20 23:45 UTC, averikitsch commented
/gcbrun

2023-03-20 23:49 UTC, merged