style: Rename django-python-hello-world samples to be unique
GoogleCloudPlatform/cloud-code-samples pull request #1230
Opened 2023-04-06 21:18 UTC by SKrupa

Currently they use the same name as the existing python-hello-world sample. As these samples are deploying different code, they should use different names. This is consistent with how the guestbook samples are defined, where the django sample use a different name than the base python ones.

2023-04-06 22:30 UTC, averikitsch requested changes

2023-04-06 22:30 UTC, averikitsch commented on python/django/python-hello-world/kubernetes-manifests/hello.deployment.yaml
>  apiVersion: apps/v1
Missing update on line 2

2023-04-06 22:49 UTC, SKrupa commented on python/django/python-hello-world/kubernetes-manifests/hello.deployment.yaml
>  apiVersion: apps/v1
whoops, fixed. Thanks!

2023-04-06 23:36 UTC, averikitsch approved these changes

2023-04-06 23:36 UTC, averikitsch commented
/gcbrun

2023-04-07 18:17 UTC, averikitsch commented
/gcbrun

2023-04-07 18:19 UTC, merged