Java, Go, Python, Node.js - update Guestbook & Hello World READMEs
GoogleCloudPlatform/cloud-code-samples pull request #713
Opened 2021-05-18 22:47 UTC by kelsk

This PR updates the Java, Go, Python, and Node samples with the same reviewed & approved content from the .NET samples (see #704 for reference).

Updates affect all *Guestbook* and *Hello World* (K8s) samples, except the Django Guestbook sample, for a total of *36 READMEs* affected.

A "What's in this sample" section has been added, including:
- updated Kubernetes Architecture diagram
- explanation of directory content

2021-05-18 22:56 UTC, kelsk commented
/gcbrun

2021-05-18 23:43 UTC, dinagraves commented on golang/go-guestbook/.readmes/intellij/README.md
> +* [What's in this sample](#what's-in-this-sample)
This link doesn't seem to work

2021-05-18 23:44 UTC, dinagraves commented on golang/go-guestbook/.readmes/intellij/README.md
> +* [What's in this sample](#what's-in-this-sample)
Should be `#whats-in-this-sample`

2021-05-18 23:46 UTC, dinagraves requested changes

2021-05-18 23:46 UTC, dinagraves commented on java/java-guestbook/.readmes/intellij/README.md
> +* [What's in this sample](#what's-in-this-sample)
```suggestion
* [What's in this sample](#whats-in-this-sample)
```

2021-05-18 23:46 UTC, dinagraves commented on nodejs/nodejs-guestbook/.readmes/intellij/README.md
> +* [What's in this sample](#what's-in-this-sample)
```suggestion
* [What's in this sample](#whats-in-this-sample)
```

2021-05-18 23:46 UTC, dinagraves commented on python/python-guestbook/.readmes/intellij/README.md
> +* [What's in this sample](#what's-in-this-sample)
```suggestion
* [What's in this sample](#whats-in-this-sample)
```

2021-05-18 23:47 UTC, kelsk commented on golang/go-guestbook/.readmes/intellij/README.md
> +* [What's in this sample](#what's-in-this-sample)
Fixed!

2021-05-18 23:49 UTC, kelsk commented
/gcbrun

2021-05-19 00:08 UTC, dinagraves approved these changes

2021-05-19 00:08 UTC, dinagraves commented
/gcbrun

2021-05-19 04:31 UTC, merged